DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255),
	pw_hash VARCHAR(255),
	is_admin BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY (id)
) ENGINE=INNODB;
